# Generated by Django 5.2.17 on 2026-08-31 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('CREATE', 'Tạo mới'), ('UPDATE', 'Chỉnh sửa'), ('DELETE', 'Xóa'), ('GRADE_CHANGE', 'Sửa điểm số'), ('CERTIFICATE_ISSUED', 'Cấp chứng nhận'), ('PERMISSION_CHANGE', 'Thay đổi quyền hạn')], max_length=30)),
                ('resource_type', models.CharField(max_length=100, verbose_name='Đối tượng tác động')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID đối tượng')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Chi tiết thay đổi')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký kiểm toán',
                'verbose_name_plural': 'Danh sách nhật ký kiểm toán',
                'ordering': ['-timestamp'],
            },
        ),
    ]
