# Generated by Django 5.2.17 on 2026-08-31 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='Họ và tên học viên')),
                ('course_or_exam_title', models.CharField(max_length=255, verbose_name='Khóa học / Chứng chỉ đạt được')),
                ('cert_code', models.CharField(max_length=100, unique=True, verbose_name='Mã số chứng nhận duy nhất')),
                ('score', models.PositiveIntegerField(default=1000, verbose_name='Điểm số đạt được')),
                ('issuer', models.CharField(default='PH Digital Education / Certiport Authorized Provider', max_length=255, verbose_name='Đơn vị cấp')),
                ('issue_date', models.DateField(verbose_name='Ngày cấp chứng nhận')),
                ('sha256_hash', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Mã băm xác thực SHA-256')),
                ('qr_verify_url', models.URLField(blank=True, verbose_name='Đường dẫn QR tra cứu')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Trạng thái hiệu lực')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chứng nhận',
                'verbose_name_plural': 'Danh sách chứng nhận',
                'ordering': ['-issue_date'],
            },
        ),
    ]
