# Generated by Django 5.2.17 on 2026-08-31 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài thi')),
                ('subject', models.CharField(choices=[('MOS_EXCEL', 'MOS Excel 2019/365'), ('MOS_WORD', 'MOS Word 2019/365'), ('MOS_POWERPOINT', 'MOS PowerPoint 2019/365'), ('IC3_GS6', 'IC3 Digital Literacy GS6'), ('PYTHON', 'Python Ứng Dụng')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=50, verbose_name='Thời gian thi (phút)')),
                ('pass_score', models.PositiveIntegerField(default=700, verbose_name='Điểm đỗ (Chuẩn 700/1000)')),
                ('total_points', models.PositiveIntegerField(default=1000, verbose_name='Thang điểm tối đa')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('options', models.JSONField(default=list, verbose_name='Danh sách phương án (A, B, C, D)')),
                ('correct_index', models.PositiveIntegerField(verbose_name='Index đáp án đúng (0-based)')),
                ('explanation', models.TextField(verbose_name='Giải thích chi tiết của chuyên gia')),
                ('skill', models.CharField(default='Kỹ năng thao tác cốt lõi', max_length=150, verbose_name='Nhóm kỹ năng')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Điểm câu hỏi')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên ngân hàng câu hỏi')),
                ('subject', models.CharField(choices=[('MOS_EXCEL', 'MOS Excel 2019/365'), ('MOS_WORD', 'MOS Word 2019/365'), ('MOS_POWERPOINT', 'MOS PowerPoint 2019/365'), ('IC3_GS6', 'IC3 Digital Literacy GS6'), ('PYTHON', 'Python Ứng Dụng')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Họ tên thí sinh tự do')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT thí sinh tự do')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Điểm đạt được (thang 1000)')),
                ('passed', models.BooleanField(default=False, verbose_name='Kết quả Đạt / Không đạt')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.exam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_index', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionbank'),
        ),
    ]
