# Generated by Django 5.2.17 on 2026-08-31 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Danh mục khóa học',
                'verbose_name_plural': 'Danh mục khóa học',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên kỹ năng')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên khóa học')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Khẩu hiệu / Tóm tắt ngắn')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Học phí ưu đãi')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Học phí gốc')),
                ('duration', models.CharField(default='3 - 5 buổi', max_length=100, verbose_name='Thời lượng')),
                ('exam_code', models.CharField(blank=True, max_length=100, verbose_name='Mã khảo thí')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='Huy hiệu nổi bật')),
                ('target_audience', models.TextField(blank=True, verbose_name='Đối tượng học viên')),
                ('pass_rate', models.CharField(default='99.2% Đỗ chứng chỉ', max_length=50, verbose_name='Tỷ lệ đỗ')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã phát hành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Danh sách khóa học',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề Module')),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài học')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung bài giảng')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Link Video bài giảng')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Thời lượng (phút)')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Xem thử miễn phí')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
