# Generated by Django 5.2.17 on 2026-08-31 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên lớp học')),
                ('start_date', models.CharField(max_length=150, verbose_name='Ngày khai giảng / Lịch học')),
                ('schedule_time', models.CharField(max_length=150, verbose_name='Ca học trong ngày')),
                ('mode', models.CharField(choices=[('ONLINE', 'Online qua Zoom / Google Meet'), ('ONE_ON_ONE', 'Kèm 1:1 Cấp Tốc'), ('OFFLINE', 'Trực tiếp tại cơ sở liên kết')], default='ONLINE', max_length=30)),
                ('total_slots', models.PositiveIntegerField(default=15, verbose_name='Tổng chỉ tiêu')),
                ('remaining_slots', models.PositiveIntegerField(default=5, verbose_name='Chỉ tiêu còn lại')),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở đăng ký'), ('ALMOST_FULL', 'Sắp đầy chỗ'), ('CLOSED', 'Đã khóa sĩ số')], default='OPEN', max_length=30)),
                ('meet_link', models.URLField(blank=True, null=True, verbose_name='Link phòng học ảo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên phụ trách')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Danh sách lớp học',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang theo học'), ('COMPLETED', 'Đã tốt nghiệp'), ('DROPPED', 'Bảo lưu / Thôi học')], default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('academic_warning_count', models.PositiveIntegerField(default=0, verbose_name='Số lần cảnh báo vắng')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.classbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ghi danh học viên',
                'verbose_name_plural': 'Danh sách ghi danh',
                'unique_together': {('user', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(verbose_name='Buổi số')),
                ('is_present', models.BooleanField(default=True, verbose_name='Có mặt')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú của GV')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.enrollment')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Bảng điểm danh',
                'unique_together': {('enrollment', 'session_number')},
            },
        ),
    ]
