import { Source, Category } from "./types";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "cat-ai",
    name: "AI & Trí tuệ nhân tạo",
    slug: "ai-tri-tue-nhan-tao",
    description: "Cập nhật ứng dụng ChatGPT, Google Gemini, Copilot và các công cụ AI hỗ trợ công việc học tập.",
    icon: "Brain",
    order: 1,
    isActive: true,
  },
  {
    id: "cat-office",
    name: "Microsoft Office & MOS",
    slug: "microsoft-office-mos",
    description: "Thủ thuật Excel, Word, PowerPoint, luyện thi chứng chỉ MOS và mẹo xử lý bảng tính thực tế.",
    icon: "FileSpreadsheet",
    order: 2,
    isActive: true,
  },
  {
    id: "cat-google",
    name: "Google Workspace & IC3",
    slug: "google-workspace-ic3",
    description: "Khai thác tối đa Google Docs, Sheets, Drive, Meet và chứng chỉ tin học quốc tế IC3.",
    icon: "Layers",
    order: 3,
    isActive: true,
  },
  {
    id: "cat-security",
    name: "An toàn thông tin & Bảo mật",
    slug: "an-toan-thong-tin",
    description: "Cảnh báo lừa đảo mạng, bảo mật tài khoản cá nhân, phòng chống mã độc và kỹ năng số an toàn.",
    icon: "ShieldAlert",
    order: 4,
    isActive: true,
  },
  {
    id: "cat-dev",
    name: "Công cụ Lập trình & Tech Trends",
    slug: "cong-cu-lap-trinh",
    description: "Công cụ GitHub, VS Code, công nghệ Web, Cloud và các xu hướng công nghệ mới nhất.",
    icon: "Code2",
    order: 5,
    isActive: true,
  },
  {
    id: "cat-productivity",
    name: "Kỹ năng số & Hiệu suất",
    slug: "ky-nang-so-hieu-suat",
    description: "Mẹo nâng cao tốc độ làm việc văn phòng, thiết kế Canva, quản lý dữ liệu và tự động hóa.",
    icon: "Zap",
    order: 6,
    isActive: true,
  },
];

export const DEFAULT_SOURCES: Source[] = [
  // 1. Microsoft Feeds
  {
    id: "src-ms-blog",
    name: "Microsoft Official Blog",
    url: "https://blogs.microsoft.com",
    feedUrl: "https://blogs.microsoft.com/feed/",
    sourceType: "RSS",
    category: "Microsoft Office & MOS",
    language: "en",
    priority: "OFFICIAL",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "src-ms-365",
    name: "Microsoft 365 Updates",
    url: "https://www.microsoft.com/en-us/microsoft-365/blog/",
    feedUrl: "https://www.microsoft.com/en-us/microsoft-365/blog/feed/",
    sourceType: "RSS",
    category: "Microsoft Office & MOS",
    language: "en",
    priority: "OFFICIAL",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "src-windows-blog",
    name: "Windows Experience Blog",
    url: "https://blogs.windows.com",
    feedUrl: "https://blogs.windows.com/feed/",
    sourceType: "RSS",
    category: "Kỹ năng số & Hiệu suất",
    language: "en",
    priority: "HIGH",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 2. Google Feeds
  {
    id: "src-google-workspace",
    name: "Google Workspace Updates",
    url: "https://workspaceupdates.googleblog.com",
    feedUrl: "https://workspaceupdates.googleblog.com/feeds/posts/default?alt=rss",
    sourceType: "ATOM",
    category: "Google Workspace & IC3",
    language: "en",
    priority: "OFFICIAL",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "src-google-ai",
    name: "Google The Keyword / AI",
    url: "https://blog.google",
    feedUrl: "https://blog.google/rss/",
    sourceType: "RSS",
    category: "AI & Trí tuệ nhân tạo",
    language: "en",
    priority: "OFFICIAL",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 3. OpenAI & AI Tech
  {
    id: "src-openai",
    name: "OpenAI News & Updates",
    url: "https://openai.com/news",
    feedUrl: "https://openai.com/news/rss.xml",
    sourceType: "RSS",
    category: "AI & Trí tuệ nhân tạo",
    language: "en",
    priority: "OFFICIAL",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 4. Cybersecurity
  {
    id: "src-bleeping-computer",
    name: "BleepingComputer Cybersecurity",
    url: "https://www.bleepingcomputer.com",
    feedUrl: "https://www.bleepingcomputer.com/feed/",
    sourceType: "RSS",
    category: "An toàn thông tin & Bảo mật",
    language: "en",
    priority: "HIGH",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 5. Developer & Tech News
  {
    id: "src-github-blog",
    name: "GitHub Official Blog",
    url: "https://github.blog",
    feedUrl: "https://github.blog/feed/",
    sourceType: "RSS",
    category: "Công cụ Lập trình & Tech Trends",
    language: "en",
    priority: "HIGH",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "src-the-verge",
    name: "The Verge Tech & AI",
    url: "https://www.theverge.com",
    feedUrl: "https://www.theverge.com/rss/index.xml",
    sourceType: "RSS",
    category: "AI & Trí tuệ nhân tạo",
    language: "en",
    priority: "NORMAL",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "src-ars-technica",
    name: "Ars Technica Technology",
    url: "https://arstechnica.com",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
    sourceType: "RSS",
    category: "Công cụ Lập trình & Tech Trends",
    language: "en",
    priority: "NORMAL",
    isActive: true,
    autoFetch: true,
    autoProcessAi: true,
    autoPublish: false,
    fetchInterval: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
